#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
# npm run check-format ||
# (
#     echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
#     false;
# )

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)


# Run Unit Tests
npm run test ||
(
    echo '❌❌ Unit Tests Failed, take a look at the output ❌❌
            View the error log and update your test or run npm run test again. 
    '
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check!'
    false;
)

# Add to pre-commit.sh
# npm audit ||
# (
#     echo '🔒🚨 Security vulnerabilities found. Please fix them before committing. 🚨🔒'
#     false;
# )

# # If everything passes... Now we can commit
# echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
