# -*- coding: utf-8 -*-
"""CoinGeckoMongoDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLc4-WDGXZIOeIOwq0QrEZZGv9hPU0T4
"""

!pip install -U pycoingecko
!pip install pandas
!pip install pymongo

from pycoingecko import CoinGeckoAPI
import pandas as pd

# cg = CoinGeckoAPI()


# class Person(object):
#     def __init__(self, id='', symbol='', name=''):
#         self.id = id
#         self.symbol = symbol
#         self.name = name

#     def as_dict(self):
#         return {'name': self.name, 'id': self.id, 'symbol': self.symbol}



# df = pd.DataFrame([x for x in cg.get_coins_list()])

cg = CoinGeckoAPI()


class Person(object):
    def __init__(self, id='', symbol='', name=''):
        self.id = id
        self.symbol = symbol
        self.name = name

    def as_dict(self):
        return {'name': self.name, 'id': self.id, 'symbol': self.symbol}


# Get the list of coins with market data sorted by market cap descending
coins = cg.get_coins_markets(vs_currency='usd', order='market_cap_desc')

# Create a DataFrame from the coin data
df = pd.DataFrame(coins)

# Extract the required fields and create a list of Person objects
persons = [Person(id=row['id'], symbol=row['symbol'], name=row['name']) for _, row in df.iterrows()]

# Example usage: Convert the list of Person objects to a list of dictionaries
person_dicts = [person.as_dict() for person in persons]

df

jsonFrame = df.to_json(orient='records')
dictFrame = df.to_dict(orient='records')

dictFrame

import pymongo
import json
from pymongo import MongoClient, InsertOne

client = pymongo.MongoClient('mongodb+srv://jarodChristiansenAdmin:oT1gi5ai!@cluster0.p6crk.mongodb.net/Crypto_Watch?retryWrites=true&w=majority')
db = client.Crypto_Watch
collection = db['assets']
requesting = []

for jsonObj in dictFrame:
    result = collection.insert_one(jsonObj)

# with open(r'assetList.json') as f:
#     for jsonObj in f:
#         myDict = json.loads(jsonObj)
#         for asset in myDict:
#             res = asset.to_dict();
#             result = collection.insert_one(res)


client.close()

with open('assetList.json', 'w') as f:
    json.dump(jsonFrame, f)

df.to_csv('CoinGeckoList.csv')