name: Running Code Coverage

on: [push, pull_request]

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "header, diff, changes, tree"
  behavior: default
